version: "3.8"

services:
  db:
    build: ./containers/mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: prosody_user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # # MYSQL_DATABASE: root
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_ROOT_PASSWORD: "yes"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  schemaspy:
    build: ./containers/schemaspy
    image: schemaspy/schemaspy
    depends_on:
      - db
    volumes:
      - ./containers/schemaspy/output:/output
      - ./containers/schemaspy/config/schemaspy.properties:/app/schemaspy.properties:ro
      - ./containers/schemaspy/config/start.sh:/app/start.sh:ro
    container_name: "schemaspy"
    command: "/bin/sh /app/start.sh"
    # command: "java -jar schemaspy.jar -vizjs "
    # command: "java -jar schemaspy.jar -connprops "characterEncoding\=utf-8"
    links:
      - db:db

  nginx_schemaspy:
    image: nginx:1.19.5-alpine
    container_name: "nginx_schemaspy"
    ports:
      - "4000:80"
    volumes:
      - ./schemaspy/output:/usr/share/nginx/html:ro
    depends_on:
      - db
  web:
      build:
        context: .
        dockerfile: ./containers/nginx/Dockerfile
      ports:
          - "8080:80"
      depends_on:
          - php
      volumes:
          - ./code:/tmp
  php:
      build:
        context: .
        dockerfile: ./containers/php/Dockerfile
      ports:
          - "8000:80"
